name: MurderMystery
main: cn.lanink.murdermystery.MurderMystery
version: "1.3.9.0-PM1E-SNAPSHOT"
api: ["Nukkit-PM1E"]
load: POSTWORLD
author: "LT_Name"
depend:
  - "MemoriesOfTime-GameCore"

permissions:
  murdermystery.user:
    default: true
  murdermystery.admin:
    default: op