name: MurderMystery
main: cn.lanink.murdermystery.MurderMystery
version: "1.0.6-SNAPSHOT"
api:
  - 1.0.9
load: POSTWORLD
author: "LT_Name"
loadbefore:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"

permissions:
  MurderMystery.command.user:
    default: true
  MurderMystery.command.admin:
    default: op