name: MurderMystery
main: cn.lanink.murdermystery.MurderMystery
version: "1.3.7-SNAPSHOT"
api: ["1.0.9"]
load: POSTWORLD
author: "LT_Name"
depend:
  - "MemoriesOfTime-GameCore"

permissions:
  murdermystery.user:
    default: true
  murdermystery.admin:
    default: op