name: MurderMystery
main: cn.lanink.murdermystery.MurderMystery
version: "1.0.3-SNAPSHOT"
api:
  - 1.0.0
load: POSTWORLD
author: "LT_Name"
depend:
  - "Tips"
  - "EconomyAPI"

permissions:
  MurderMystery.command.user:
    default: true
  MurderMystery.command.admin:
    default: op