name: MurderMystery
main: cn.lanink.murdermystery.MurderMystery
version: "1.0.7-SNAPSHOT"
api: ["1.0.9", "1.0.11"]
load: POSTWORLD
author: "LT_Name"
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"
loadbefore:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"

permissions:
  MurderMystery.command.user:
    default: true
  MurderMystery.command.admin:
    default: op