name: MurderMystery
main: cn.lanink.murdermystery.MurderMystery
version: "1.1.0"
api: ["1.0.9", "1.0.11"]
load: POSTWORLD
author: "LT_Name"
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"
loadbefore:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"

permissions:
  murdermystery.user:
    default: true
  murdermystery.admin:
    default: op